# Generated by Django 4.2.4 on 2023-09-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_news_options_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
